global:
    image: oven/bun
    
    trigger:
        branch:
            - "*"

jobs:
    - name: Init
      commands:
          - bun c react
          - ls -lah react/
      artifacts:
        - name: react
        
    - name: Dev
      commands:
          - cd react
          - bun run dev
      resources:
          - name: react
